//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashChecker.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashChecker.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments:
        ///no arguments : Standatd interface
        ///&lt;path to exe&gt; &lt;filepath&gt; : validate entries in &lt;filepath&gt; checksum file;
        ///&lt;path to exe&gt; -comp2clipboard &lt;filepath&gt; : chack if file &lt;filepath&gt; has hash equal to hash in clipboard
        ///&lt;path to exe&gt; /h : show this help.
        /// </summary>
        internal static string CommandLineArgumentsHelp {
            get {
                return ResourceManager.GetString("CommandLineArgumentsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be bigger than fileSize.
        /// </summary>
        internal static string HashChecker_Must_not_be_bigger_than_fileSize {
            get {
                return ResourceManager.GetString("HashChecker_Must_not_be_bigger_than_fileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Checker.
        /// </summary>
        internal static string HashChecker_setFormToNormal_Hash_Checker {
            get {
                return ResourceManager.GetString("HashChecker_setFormToNormal_Hash_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported mode.
        /// </summary>
        internal static string HashChecker_Unsupported_mode {
            get {
                return ResourceManager.GetString("HashChecker_Unsupported_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyBig {
            get {
                object obj = ResourceManager.GetObject("KeyBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openfolderHS {
            get {
                object obj = ResourceManager.GetObject("openfolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to registry while saving data.
        /// </summary>
        internal static string OptionsForm_bOK_Click_Error_writing_to_registry_while_saving_data {
            get {
                return ResourceManager.GetString("OptionsForm_bOK_Click_Error_writing_to_registry_while_saving_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: click &apos;Options&apos; and select associations. After that you can just doubleclick checksum files (*.sfv, *.md5, *.sha1, etc) in Windows Explorer.
        /// </summary>
        internal static string SimpleUsageHelp {
            get {
                return ResourceManager.GetString("SimpleUsageHelp", resourceCulture);
            }
        }
    }
}
